[uat-webservers]
172.31.91.153 ansible_ssh_user='ec2-user'
ansible_ssh_private_key_file=C:\Users\DELL\.ssh\xav_aws.pem
172.31.94.34 ansible_ssh_user='ec2-user'
ansible_ssh_private_key_file=C:\Users\DELL\.ssh\xav_aws.pem